-- base relations, no foreign keys 
CREATE TABLE EMPLOYEE(
	SSN INT NOT NULL,
	Fname VARCHAR(15) NOT NULL, 
	Lname VARCHAR(15) NOT NULL,
	Hire_Date DATE NOT NULL,
	PRIMARY KEY(SSN)
);
CREATE TABLE PROJECT( 
	Project_No INT NOT NULL,
	Pname VARCHAR(20) NOT NULL,
	Stat VARCHAR(10) NOT NULL,
	PRIMARY KEY(Project_No)
);

CREATE TABLE CONSOLE(
	ConsoleID INT NOT NULL,
	Release_Date DATE NOT NULL,
	Price INT NOT NULL,
	Title VARCHAR(50) NOT NULL,
	Units_Sold INT,
	PRIMARY KEY(ConsoleID)
);

CREATE TABLE PLAYER(
	PlayerID VARCHAR(20) NOT NULL,
	FName VARCHAR(20),
	LName VARCHAR(20),
	PRIMARY KEY(PlayerID)
);

CREATE TABLE GAME(
	GameID INT NOT NULL,
	Release_Date DATE NOT NULL,
	Price INT NOT NULL,
	Title VARCHAR(40) NOT NULL,
	Genre VARCHAR(20) NOT NULL,
	Units_Sold INT,
	PRIMARY KEY(GameID)
);

-- specializations, includes foreign keys
-- @block
CREATE TABLE GAME_DEV(
	Game_Dev_ID INT NOT NULL,
	Game_Expertise VARCHAR(15) NOT NULL,
	PRIMARY KEY(Game_Dev_ID),
	FOREIGN KEY(Game_Dev_ID) REFERENCES EMPLOYEE(SSN)
);

CREATE TABLE SYS_ENG(
	Sys_Dev_ID INT NOT NULL,
	System_Expertise INT NOT NULL,
	PRIMARY KEY(Sys_Dev_ID),
	FOREIGN KEY(Sys_Dev_ID) REFERENCES EMPLOYEE(SSN),
	FOREIGN KEY(System_Expertise) REFERENCES CONSOLE(ConsoleID)
);

CREATE TABLE CONSOLE_PROJ(
	Console_Proj_ID INT NOT NULL,
	ConsoleID INT NOT NULL,
	Cons_Proj_Mgr_SSN INT NOT NULL,
	PRIMARY KEY(Console_Proj_ID),
	FOREIGN KEY(Console_Proj_ID) REFERENCES PROJECT(Project_No),
	FOREIGN KEY(ConsoleID) REFERENCES CONSOLE(ConsoleID),
	FOREIGN KEY(Cons_Proj_Mgr_SSN) REFERENCES SYS_ENG(Sys_Dev_ID)
);

CREATE TABLE GAME_PROJ(
	Game_Proj_ID INT NOT NULL,
	GameID INT NOT NULL,
	Game_Proj_Mgr_SSN INT NOT NULL,
	PRIMARY KEY(Game_Proj_ID),
	FOREIGN KEY(Game_Proj_ID) REFERENCES PROJECT(Project_No),
	FOREIGN KEY(GameID) REFERENCES GAME(GameID),
	FOREIGN KEY(Game_Proj_Mgr_SSN) REFERENCES GAME_DEV(Game_Dev_ID)
);

-- relationships, includes specializations and base relations
-- @block
CREATE TABLE DEVELOPS(
	Game_Dev_ID INT NOT NULL,
	Game_Proj_ID INT NOT NULL,
	PRIMARY KEY(Game_Dev_ID, Game_Proj_ID),
	FOREIGN KEY(Game_Dev_ID) REFERENCES GAME_DEV(Game_Dev_ID),
	FOREIGN KEY(Game_Proj_ID) REFERENCES GAME_PROJ(Game_Proj_ID)
);

CREATE TABLE ENGINEERS(
	Sys_Eng_ID INT NOT NULL,
	Cons_Proj_ID INT NOT NULL,
	PRIMARY KEY(Sys_Eng_ID, Cons_Proj_ID),
	FOREIGN KEY(Sys_Eng_ID) REFERENCES SYS_ENG(Sys_Dev_ID),
	FOREIGN KEY(Cons_Proj_ID) REFERENCES CONSOLE_PROJ(Console_Proj_ID)
);

CREATE TABLE OWNED_CONSOLES(
	PlayerID VARCHAR(20) NOT NULL,
	ConsoleID INT NOT NULL,
	PRIMARY KEY(PlayerID, ConsoleID),
	FOREIGN KEY(PlayerID) REFERENCES PLAYER(PlayerID),
	FOREIGN KEY(ConsoleID) REFERENCES CONSOLE(ConsoleID)
);
-- @block

CREATE TABLE COMPATIBLE_GAME_CONS(
	GameID INT NOT NULL,
	ConsoleID INT NOT NULL,
	PRIMARY KEY(GameID, ConsoleID),
	FOREIGN KEY(GameID) REFERENCES GAME(GameID),
	FOREIGN KEY(ConsoleID) REFERENCES CONSOLE(ConsoleID)
);

CREATE TABLE OWNED_GAME(
	PlayerID VARCHAR(20) NOT NULL,
	GameID INT NOT NULL,
	Console_Num INT NOT NULL,
	PRIMARY KEY(PlayerID, GameID, Console_Num),
	FOREIGN KEY(PlayerID) REFERENCES PLAYER(PlayerID),
	FOREIGN KEY(GameID, Console_Num) REFERENCES COMPATIBLE_GAME_CONS(GameID, ConsoleID)
);













