-- @block
LOAD DATA LOCAL INFILE 'Instance/employee.txt' INTO TABLE EMPLOYEE
    FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE 'Instance/project.txt' INTO TABLE PROJECT
    FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE 'Instance/console.txt' INTO TABLE CONSOLE
    FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE 'Instance/player.txt' INTO TABLE PLAYER
    FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE 'Instance/game.txt' INTO TABLE GAME
    FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE 'Instance/game_dev.txt' INTO TABLE GAME_DEV
    FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE 'Instance/sys_eng.txt' INTO TABLE SYS_ENG
    FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE 'Instance/console_proj.txt' INTO TABLE CONSOLE_PROJ
    FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE 'Instance/game_proj.txt' INTO TABLE GAME_PROJ
    FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE 'Instance/develops.txt' INTO TABLE DEVELOPS
    FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE 'Instance/engineers.txt' INTO TABLE ENGINEERS
    FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE 'Instance/owned_consoles.txt' INTO TABLE OWNED_CONSOLES
    FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE 'Instance/compatible_game_cons.txt' INTO TABLE COMPATABLE_GAME_CONS
    FIELDS TERMINATED BY ',';

LOAD DATA LOCAL INFILE 'Instance/owned_game.txt' INTO TABLE OWNED_GAME
    FIELDS TERMINATED BY ',';